### ISSUE TITLE
加载进度

### ISSUE THREAD

**Issue by lyatcomit** [casatwy/CTVideoPlayerView#12]
请问大神，我怎样知道视频已经加载了多少？

**Comment by casatwy** [comment]
这个组件现在还不提供在边下边播时告知加载进度的功能，你需要用AVURLAsset的reourceLoader来实现。

发自我的 iPhone

在 2016年8月27日，10:13，lyatcomit <notifications@github.com<mailto:notifications@github.com>> 写道：


请问大神，我怎样知道视频已经加载了多少？

―
