### ISSUE TITLE
_videoView.shouldChangeOrientationToFitVideo 在播放的时候再改变无效

### ISSUE THREAD

**Issue by lyatcomit** [casatwy/CTVideoPlayerView#14]
shouldChangeOrientationToFitVideo 在播放的时候再改变无效

**Comment by casatwy** [comment]
我知道你是想做全屏功能是吧？我刚刚已经开发了全屏功能了，直接调用enterFullScreen和exitFullScreen就可以。已经发布在1.2.1版本中了
