### ISSUE TITLE
could not play the media file with MPEG-4

### ISSUE THREAD

**Issue by zhangnet** [casatwy/CTVideoPlayerView#15]
I download a video file with url and store in local path,when I play it with CTVideoPlayerView,the log output:
Error Domain=AVFoundationErrorDomain Code=-11833 "无法解码" UserInfo={NSLocalizedFailureReason=找不到此媒体所需的解码器。, NSUnderlyingError=0x7fcc90e41f40 {Error Domain=NSOSStatusErrorDomain Code=-12945 "(null)"}, AVErrorMediaTypeKey=soun, NSLocalizedDescription=无法解码}

**Comment by casatwy** [comment]
这个文件可能只是后缀名是MP4，编码方式不是MP4的编码方式吧？因为报的是无法解码的错误。CTVideoPlayerView的解码器用的是iOS系统默认的

**Comment by zhangnet** [comment]
我用QuickTime 影片检查器看到的格式显示是MPEG-4

发自我的 iPhone

在 2016年9月22日，下午12:12，Casa Taloyum <notifications@github.com<mailto:notifications@github.com>> 写道：


这个文件可能只是后缀名是MP4，编码方式不是MP4的编码方式吧？因为报的是无法解码的错误。CTVideoPlayerView的解码器用的是iOS系统默认的

―

**Comment by casatwy** [comment]
这就很蛋疼了，因为我写CTVideoViewPlayer的时候，并没有涉及解码器的部分，用的都是原生的，也许将来我会添加第三方解码器模块来解决这个问题。

**Comment by zhangnet** [comment]
还是感谢你的付出，你的代码让我很有收获

发自我的 iPhone

在 2016年9月22日，下午2:01，Casa Taloyum <notifications@github.com<mailto:notifications@github.com>> 写道：


这就很蛋疼了，因为我写CTVideoViewPlayer的时候，并没有涉及解码器的部分，用的都是原生的，也许将来我会添加第三方解码器模块来解决这个问题。

―
