### ISSUE TITLE
退出时有崩溃

### ISSUE THREAD

**Issue by hoowang** [casatwy/CTVideoPlayerView#23]
感谢作者提供如此给力的开源项目。自从上次升级以后，截止当前版本，播放器销毁时有崩溃。具体log如下：observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x61000003f940> (
<NSKeyValueObservance 0x610000051970: Observer: 0x7fba66e10510, Key path: player.currentItem.status, Options: <New: YES, Old: NO, Prior: NO> Context: 0x105fd6388, Property: 0x608000092890>
<NSKeyValueObservance 0x610000051c70: Observer: 0x7fba66e10510, Key path: player.currentItem.duration, Options: <New: YES, Old: NO, Prior: NO> Context: 0x105fd6388, Property: 0x6100000954a0>
<NSKeyValueObservance 0x6100000521b0: Observer: 0x7fba66e10510, Key path: layer.readyForDisplay, Options: <New: YES, Old: NO, Prior: NO> Context: 0x105fd6388, Property: 0x610000095b80>

应该是observer没有正确移除导致。

**Comment by casatwy** [comment]
你是initWithFrame的用法导致的crash么？如果是的话，这个问题已经在新版解决了。

如果不是的话，你能不能把你使用的语句给我看一下？

发自我的 iPhone

在 2016年11月15日，23:23，coderHooge <notifications@github.com<mailto:notifications@github.com>> 写道：


感谢作者提供如此给力的开源项目。自从上次升级以后，截止当前版本，播放器销毁时有崩溃。具体log如下：observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x61000003f940> (
<NSKeyValueObservance 0x610000051970: Observer: 0x7fba66e10510, Key path: player.currentItem.status, Options: <New: YES, Old: NO, Prior: NO> Context: 0x105fd6388, Property: 0x608000092890>
<NSKeyValueObservance 0x610000051c70: Observer: 0x7fba66e10510, Key path: player.currentItem.duration, Options: <New: YES, Old: NO, Prior: NO> Context: 0x105fd6388, Property: 0x6100000954a0>
<NSKeyValueObservance 0x6100000521b0: Observer: 0x7fba66e10510, Key path: layer.readyForDisplay, Options: <New: YES, Old: NO, Prior: NO> Context: 0x105fd6388, Property: 0x610000095b80>

应该是observer没有正确移除导致。

―

**Comment by casatwy** [comment]
或者你在demo的tableview列表里给我提一个pr来复现这个crash？

发自我的 iPhone

在 2016年11月15日，23:23，coderHooge <notifications@github.com<mailto:notifications@github.com>> 写道：


感谢作者提供如此给力的开源项目。自从上次升级以后，截止当前版本，播放器销毁时有崩溃。具体log如下：observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x61000003f940> (
<NSKeyValueObservance 0x610000051970: Observer: 0x7fba66e10510, Key path: player.currentItem.status, Options: <New: YES, Old: NO, Prior: NO> Context: 0x105fd6388, Property: 0x608000092890>
<NSKeyValueObservance 0x610000051c70: Observer: 0x7fba66e10510, Key path: player.currentItem.duration, Options: <New: YES, Old: NO, Prior: NO> Context: 0x105fd6388, Property: 0x6100000954a0>
<NSKeyValueObservance 0x6100000521b0: Observer: 0x7fba66e10510, Key path: layer.readyForDisplay, Options: <New: YES, Old: NO, Prior: NO> Context: 0x105fd6388, Property: 0x610000095b80>

应该是observer没有正确移除导致。

―

**Comment by hoowang** [comment]
我在项目中使用的过程中发现了又这样的bug。所以我下载最新项目的demo。在demo第一项Single Remote Video列表项点击，进入第一个videoplay 页面，此时不管是否点击play按钮，只要点击back，pop页面的时候（经测试 进入任何一个demo页面， pop的时候都会出现），必定出现这个bug。测试环境：Xcode 8.1，iPhone 7模拟器。
debug log：Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'An instance 0x7fe39f70df00 of class CTVideoView was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x6080002398e0> (
<NSKeyValueObservance 0x6080002465a0: Observer: 0x7fe39f70df00, Key path: player.currentItem.status, Options: <New: YES, Old: NO, Prior: NO> Context: 0x10518d388, Property: 0x6000000918f0>
<NSKeyValueObservance 0x6080002463f0: Observer: 0x7fe39f70df00, Key path: player.currentItem.duration, Options: <New: YES, Old: NO, Prior: NO> Context: 0x10518d388, Property: 0x608000091490>
<NSKeyValueObservance 0x608000246600: Observer: 0x7fe39f70df00, Key path: layer.readyForDisplay, Options: <New: YES, Old: NO, Prior: NO> Context: 0x10518d388, Property: 0x608000090ef0>
)'
这个bug应该是从version 1.3.0出现，version 1.2.9没有这个问题。

**Comment by casatwy** [comment]
卧槽？我赶紧看看

发自我的 iPhone

在 2016年11月16日，10:14，coderHooge <notifications@github.com<mailto:notifications@github.com>> 写道：


我在项目中使用的过程中发现了又这样的bug。所以我下载最新项目的demo。在demo第一项Single Remote Video列表项点击，进入第一个videoplay 页面，此时不管是否点击play按钮，只要点击back，pop页面的时候（经测试 进入任何一个demo页面， pop的时候都会出现），必定出现这个bug。测试环境：Xcode 8.1，iPhone 7模拟器。
debug log：Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'An instance 0x7fe39f70df00 of class CTVideoView was deallocated while key value observers were still registered with it. Current observation info: (
Context: 0x10518d388, Property: 0x6000000918f0>
Context: 0x10518d388, Property: 0x608000091490>
Context: 0x10518d388, Property: 0x608000090ef0>
)'
这个bug应该是从version 1.3.0出现，version 1.2.9没有这个问题。

―

**Comment by casatwy** [comment]
已经在1.3.2中解决掉这个bug了，1.3.2已经发版。
