### ISSUE TITLE
cocoaPods 搜索不到1.3.1

### ISSUE THREAD

**Issue by hoowang** [casatwy/CTVideoPlayerView#24]
刚刚搜索打算升级一下，但是新版本搜索不到。麻烦大神处理一下。
如下：
-> CTVideoPlayerView (1.3.0)
   A video view for iOS which can play multy video at the same time, and can
   download and manage video file.
   pod 'CTVideoPlayerView', '~> 1.3.0'
   - Homepage: https://github.com/casatwy/CTVideoPlayerView
   - Source:   https://github.com/casatwy/CTVideoPlayerView.git
   - Versions: 1.3.0, 1.2.9, 1.2.7, 1.2.6, 1.2.4, 1.2.3, 1.2.2, 1.2.1, 1.2.0,
   1.1.9, 1.1.8, 1.1.7, 1.1.6, 1.1.5, 1.1.4, 1.1.3, 1.1.2, 1.1.1, 1.1.0, 1.0.9,
   1.0.8, 1.0.7, 1.0.6, 1.0.5, 1.0.4, 1.0.3 [master repo]
(END)

**Comment by casatwy** [comment]
你直接pod 'CTVideoPlayerView’就可以了，记得更新一下cocoapods的master的repo。1.3.1我已经提上去了的。

在 2016年11月16日，上午11:52，coderHooge <notifications@github.com<mailto:notifications@github.com>> 写道：


刚刚搜索打算升级一下，但是新版本搜索不到。麻烦大神处理一下。
如下：
-> CTVideoPlayerView (1.3.0)
A video view for iOS which can play multy video at the same time, and can
download and manage video file.
pod 'CTVideoPlayerView', '~> 1.3.0'

  *   Homepage: https://github.com/casatwy/CTVideoPlayerView
  *   Source: https://github.com/casatwy/CTVideoPlayerView.git
  *   Versions: 1.3.0, 1.2.9, 1.2.7, 1.2.6, 1.2.4, 1.2.3, 1.2.2, 1.2.1, 1.2.0,
1.1.9, 1.1.8, 1.1.7, 1.1.6, 1.1.5, 1.1.4, 1.1.3, 1.1.2, 1.1.1, 1.1.0, 1.0.9,
1.0.8, 1.0.7, 1.0.6, 1.0.5, 1.0.4, 1.0.3 [master repo]
(END)
