### ISSUE TITLE
建议增加一个回调接口指示播放失败

### ISSUE THREAD

**Issue by hoowang** [casatwy/CTVideoPlayerView#26]
如果可以，希望作者能增加一个回调告知用户播放失败。同时建议能有一个timeout配置的接口。感谢作者的贡献。

**Comment by casatwy** [comment]
我最近比较忙，可能要到周末才能给到～

**Comment by hoowang** [comment]
非常感谢！

**Comment by casatwy** [comment]
在CTVideoViewOperationDelegate里有个 - (void)videoViewStalledWhilePlaying:(CTVideoView *)videoView;

播放过程中如果因为网络问题无法继续播放了，就会调到这里。
