### ISSUE TITLE
方法找不到问题

### ISSUE THREAD

**Issue by JiaDingYi** [casatwy/CTVideoPlayerView#3]
`[self.videoTable updateValue:@(CTVideoRecordStatusPaused) forKey:@"status" whereKey:@"remoteUrl" inList:remoteUrlList error:NULL];`

`return [self.videoTable findAllWithKeyName:@"status" value:@(status) error:NULL];`

**Comment by casatwy** [comment]
重新pod update一下，CTPersistance有升级。
