### ISSUE TITLE
Full screen landscape

### ISSUE THREAD

**Issue by byroncoetsee** [casatwy/CTVideoPlayerView#33]
Hi there,

Thank you for making this - it's great :)

**Is there a way to make a video go fullscreen landscape even while the phone is still in portrait?**

Even if I transform the video and then use `enterFullscreen()`, it rotates the video back and makes it just across the middle of the screen (when in portrait).

**Comment by casatwy** [comment]
in `CTVideoView+FullScreen.m : - (void)enterFullScreen`，I will check the size of video.

if the width of video is larger than the height, I will rotate the video when enter full screen, even if the phone is in portrait.
`- (void)enterFullScreen
{
    self.isFullScreen = YES;
    
    CGFloat videoWidth = [[[self.asset tracksWithMediaType:AVMediaTypeVideo] firstObject] naturalSize].width;
    CGFloat videoHeight = [[[self.asset tracksWithMediaType:AVMediaTypeVideo] firstObject] naturalSize].height;
    
    CATransform3D transform = CATransform3DMakeRotation(0.0 / 180.0 * M_PI, 0.0, 0.0, 1.0);
    if ([self.asset CTVideoView_isVideoPortraint]) {
        if (videoWidth < videoHeight) {
            if (self.transform.b != 1 || self.transform.c != -1) {
                transform = CATransform3DMakeRotation(90.0 / 180.0 * M_PI, 0.0, 0.0, 1.0);
            }
        }
    } else {
        if (videoWidth > videoHeight) {
            if (self.transform.b != 1 || self.transform.c != -1) {
                transform = CATransform3DMakeRotation(90.0 / 180.0 * M_PI, 0.0, 0.0, 1.0);
            }
        }
    }
    [self animateToFullScreenWithTransform:transform];
}`
