### ISSUE TITLE
import not working correctly with cocoapods

### ISSUE THREAD

**Issue by henry63** [casatwy/CTVideoPlayerView#37]
Tried to make a project with cocoapod

Seems thzat CTVideoViewCommonHeader.h is not in thep od

Here is the .h header 
#import <UIKit/UIKit.h>
#import "CTVideoView.h"
!! <CTVideoPlayerView/CTVideoViewCommonHeader.h> is not in the pod !
In the objectivec

@property (nonatomic) CTVideoView *videoView ;

self.videoView = [[CTVideoView alloc] init];

 self.videoView.frame = self.view.frame ; // CGRectMake(0,0,100,100);
 [self.view addSubview:self.videoView];
    
 self.videoView.videoUrl = [NSURL URLWithString:kURLTest1 ]; // mp4 playable → property videoUrl not fonud on object of type ' CTvideoView *'
  [self.videoView play]; → no visible @interface for 'CtvideoPBView' declares the selector 'play'

**Comment by casatwy** [comment]
😂seems thats impossible...
