### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by jackiilong** [casatwy/CTVideoPlayerView#39]
CTVideoPlayerView/CTVideoView/CTVideoView/Components/DownloadManager/CTVideoDownloadManager.m:230:94: Sending 'void (^)(NSProgress * _Nonnull __strong)' to parameter of incompatible type 'NSProgress *__autoreleasing  _Nullable * _Nullable'

**Comment by jackiilong** [comment]
using afnetworking 2.6.3 .

**Comment by casatwy** [comment]
ctvideoplayerview不支持afnetworking2

发自我的 iPhone

在 2017年8月12日，下午1:40，JackiiLong <notifications@github.com<mailto:notifications@github.com>> 写道：


using afnetworking 2.6.3 .
