### ISSUE TITLE
Property 'ct_size', 'ct_width', 'ct_height' not found on object of type 'UIView *'

### ISSUE THREAD

**Issue by isurukej** [casatwy/CTVideoPlayerView#40]
How to fix this issue?
Please help me.

**Comment by casatwy** [comment]
'pod repo update' then 'pod update'

that means use the latest version of HandyFrame, and it will fix this issue.

发自我的 iPhone

在 2017年9月17日，下午3:12，Isuru Jayathissa <notifications@github.com<mailto:notifications@github.com>> 写道：


How to fix this issue?
Please help me.

**Comment by isurukej** [comment]
Thanks your help.
