### ISSUE TITLE
视频播放完后不走videoViewDidFinishPlaying回调

### ISSUE THREAD

**Issue by Batxent** [casatwy/CTVideoPlayerView#41]
如标题

**Comment by casatwy** [comment]
能在这个工程的DemoControllers里面给出复现代码么？

**Comment by casatwy** [comment]
我这里测试下来是能够走得到回调的

在PlayControlViewController里面添加`- (void)videoViewDidFinishPlaying:(CTVideoView *)videoView`方法的实现，然后运行应用，点击Slide Play Control，播放完视频时候是会走到的。

**Comment by Batxent** [comment]
@casatwy 我之前也是能走，但是最近这个方法不走了，我也不知道是什么原因导致的

**Comment by Batxent** [comment]
@casatwy 我在CTVideoView的子类中写了这句： [[NSNotificationCenter defaultCenter] removeObserver:self]; 原因就在此了。
