### ISSUE TITLE
Missing Method

### ISSUE THREAD

**Issue by zhaiyuhao** [casatwy/CTVideoPlayerView#6]
In class CTVideoDataCenter.m

- (void)startDownloadRemoteUrlList:(NSArray *)remoteUrlList completion:(void (^)(void))completion
{
    [self.videoTable updateValue:@(CTVideoRecordStatusWaitingForDownload) forKey:@"status" whereKey:@"remoteUrl" inList:remoteUrlList error:NULL];
    if (completion) {
        completion();
    }
}

- (void)pauseRecordWithRemoteUrlList:(NSArray *)remoteUrlList completion:(void (^)(void))completion
{
     [self.videoTable updateValue:@(CTVideoRecordStatusPaused) forKey:@"status" whereKey:@"remoteUrl" inList:remoteUrlList error:NULL];
    if (completion) {
        completion();
    }
}

There is no this method :   updateValue: forKey: whereKey:  inList: error:

- (NSArray<id<CTPersistanceRecordProtocol>> *)recordListWithStatus:(CTVideoRecordStatus)status
{
    return [self.videoTable findAllWithKeyName:@"status" value:@(status) error:NULL];
}

There is no this method :  findAllWithKeyName: value: error:

**Comment by casatwy** [comment]
you should run 'pod update', I have released a new version of CTPersistance.

???? iPhone

? 2016?6?20??15:40?zhaiyuhao <notifications@github.com<mailto:notifications@github.com>> ???


In class CTVideoDataCenter.m

  *   (void)startDownloadRemoteUrlList:(NSArray *)remoteUrlList completion:(void (^)(void))completion
{
[self.videoTable updateValue:@(CTVideoRecordStatusWaitingForDownload) forKey:@"status" whereKey:@"remoteUrl" inList:remoteUrlList error:NULL];
if (completion) {
completion();
}
}

  *   (void)pauseRecordWithRemoteUrlList:(NSArray *)remoteUrlList completion:(void (^)(void))completion
{
[self.videoTable updateValue:@(CTVideoRecordStatusPaused) forKey:@"status" whereKey:@"remoteUrl" inList:remoteUrlList error:NULL];
if (completion) {
completion();
}
}

There is no this method : updateValue: forKey: whereKey: inList: error:

  *   (NSArray> *)recordListWithStatus:(CTVideoRecordStatus)status { return [self.videoTable findAllWithKeyName:@"status" value:@(status) error:NULL]; }

There is no this method : findAllWithKeyName: value: error:

-
