### ISSUE TITLE
git clone 下来运行错误

### ISSUE THREAD

**Issue by ryokinki** [casatwy/CTVideoPlayerView#7]
PhaseScriptExecution 📦\ Check\ Pods\ Manifest.lock /Users/ios/Library/Developer/Xcode/DerivedData/CTVideoView-gwmiwslchfcwozageloqcjhgajdy/Build/Intermediates/CTVideoView.build/Debug-iphonesimulator/CTVideoView.build/Script-C7F799C8385037A3FAE95CAE.sh
    cd /Users/ios/Desktop/CTVideoPlayerView
    /bin/sh -c /Users/ios/Library/Developer/Xcode/DerivedData/CTVideoView-gwmiwslchfcwozageloqcjhgajdy/Build/Intermediates/CTVideoView.build/Debug-iphonesimulator/CTVideoView.build/Script-C7F799C8385037A3FAE95CAE.sh

diff: /../Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.
不知道是什么问题,缺少文件么?

**Comment by casatwy** [comment]
你pod install了么？

**Comment by ryokinki** [comment]
哦,最后pod install解决了,不过由于AFN更新了,其中一些调用方法发生了变动,屏蔽了两个报红方法,播放器可以正常运行了,3q

**Comment by casatwy** [comment]
不应该啊，我这边AFNetworking3.1.0，没有任何报红的方法

**Comment by ryokinki** [comment]
CTVideoManager里面,  - (void)resumeDownloadWithUrl:(NSURL *)url   和   - (void)downloadWithUrl:(NSURL *)url  这两个方法,调用AFN的[self.sessionManager downloadTaskWithRequest:request
                                                                                 progress:^(NSProgress * _Nonnull downloadProgress) .....会报红,貌似这个progress没有回调了,sessionManager只让传递NSProgress,所以出错;   


我进入sessionManager查看了下这个方法
- (NSURLSessionDownloadTask *)downloadTaskWithRequest:(NSURLRequest *)request
                                             progress:(NSProgress * __autoreleasing *)progress
                                          destination:(NSURL * (^)(NSURL *targetPath, NSURLResponse *response))destination
                                    completionHandler:(void (^)(NSURLResponse *response, NSURL *filePath, NSError *error))completionHandler;
貌似progress不是以block的形式传入的导致错误

**Comment by casatwy** [comment]
你的AFN是3.1.0的吗？

**Comment by ryokinki** [comment]
这个怎么不知道怎么查看啊,我只是用你的Profile里面的库,直接pod install的,你的里面是  
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'CTVideoView' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CTVideoView
  pod "AFNetworking"
  pod "CTPersistance"
  pod "HandyFrame"

end

**Comment by casatwy** [comment]
你cd进~/.cocoapods/repos/master，然后git pull origin master，然后再回项目pod update一下。

**Comment by ryokinki** [comment]
照楼主的方法做了,
为啥Podfile自动导入的是低版本的
- AFNetworking, 2.6.1
      - CTPersistance, 0.1.11
      - HandyFrame, 1.0.2
索性,直接在Podfile里面改为 pod 'AFNetworking', '~> 3.0'以后,用 
pod update --verbose --no-repo-update才最终保持AFN最新,pod update 没反应.
更新后没有报错了

就是不知为啥自动导入的是低版本的...在看楼主写的RTNetworking,写的非常好.

**Comment by casatwy** [comment]
你是不是在你自己的项目里面引用CTPlayerView的？你直接在CTPlayerView这个项目里面pod install呢？

**Comment by ryokinki** [comment]
是在CTVideoPlayerView项目里面,pod install的,也有可能是我pod安装的不正确,导致的.
我只是这样安装的
gem sources -a http://ruby.taobao.org/
sudo gem install cocoapods
可能安装缺少了一些步骤导致的问题

**Comment by casatwy** [comment]
淘宝源已经不可用了，装cocoapods的时候gem source要换一个源。

**Comment by ryokinki** [comment]
ok
