### ISSUE TITLE
播放进度条

### ISSUE THREAD

**Issue by lyatcomit** [casatwy/CTVideoPlayerView#9]
我想播放的时候有播放进度条，拖动进度条改变视频播放的位置，怎么弄？多谢！

**Comment by casatwy** [comment]
CTVideoView有一个，[time的category](https://github.com/casatwy/CTVideoPlayerView/blob/master/CTVideoView/CTVideoView/Categories/CTVideoView/Time/CTVideoView%2BTime.h)

你通过`- (void)setShouldObservePlayTime:(BOOL)shouldObservePlayTime withTimeGapToObserve:(CGFloat)timeGapToObserve`设置shouldObservePlayTime为YES，以及监听的间隔（每隔0.5秒告知一次当前播放时间还是每隔1秒告知一次播放时间，这个间隔你可以自己定）。

然后把timeDelegate赋值过去，这样你就会知道当前视频总时长、当前视频播放的时间，根据这个你就能绘制出进度条。

最后这个category下有`- (void)moveToSecond:(CGFloat)second shouldPlay:(BOOL)shouldPlay`方法，拖动进度条之后，把要跳转的秒数，和跳转之后是否要播放传给这个函数就可以了。
